name: Assignment 5 
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout  
          uses: actions/checkout@v2
          with:
            repository: tibaramadhan/wildfly
            
            submodules: 'true'
            #path: './depencies/vtk'
            ref: dd05d118217fe71a940965305cccffdb8fc5086a
        - name: Set up JDK 8
          uses: actions/setup-java@v3
          with:
            java-version: '8'
            distribution: 'adopt'
            cache: maven
        - name: Build project with Maven
          run: mvn -B package --file pom.xml
        - run: mvn test-compile -pl undertow -am
        - run: mvn -pl undertow test -Dtest=org.wildfly.extension.undertow.UndertowSubsystemTestCase#testRuntime
        - run: mvn -pl undertow edu.illinois:nondex-maven-plugin:1.1.2:nondex -Dtest=org.wildfly.extension.undertow.UndertowSubsystemTestCase#testRuntime


